import { Property } from "@/types";

export const mockProperties: Property[] = [
  {
    id: "1",
    seller_id: "seller-1",
    address: "123 Main St",
    city: "San Francisco", 
    state: "CA",
    zip_code: "94102",
    bedrooms: 3,
    bathrooms: 2,
    square_feet: 1500,
    property_type: 'single_family',
    asking_price: 1200000,
    estimated_value: 1500000,
    status: 'active',
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=400&h=300&fit=crop&crop=center"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    seller_id: "seller-2", 
    address: "456 Oak Ave",
    city: "Austin",
    state: "TX",
    zip_code: "78701",
    bedrooms: 4,
    bathrooms: 3,
    square_feet: 2200,
    property_type: 'single_family',
    asking_price: 750000,
    estimated_value: 950000,
    status: 'active',
    images: ["https://images.unsplash.com/photo-1572120360610-d971b9d7767c?w=400&h=300&fit=crop&crop=center"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    seller_id: "seller-3",
    address: "789 Pine Ln", 
    city: "Miami",
    state: "FL",
    zip_code: "33101",
    bedrooms: 5,
    bathrooms: 4,
    square_feet: 3000,
    property_type: 'single_family',
    asking_price: 950000,
    estimated_value: 1200000,
    status: 'active',
    images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400&h=300&fit=crop&crop=center"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    seller_id: "seller-4",
    address: "101 Maple Dr",
    city: "Denver", 
    state: "CO",
    zip_code: "80201",
    bedrooms: 2,
    bathrooms: 2,
    square_feet: 1300,
    property_type: 'single_family',
    asking_price: 600000,
    estimated_value: 750000,
    status: 'active',
    images: ["https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=400&h=300&fit=crop&crop=center"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    seller_id: "seller-5",
    address: "212 Birch Rd",
    city: "Seattle",
    state: "WA", 
    zip_code: "98101",
    bedrooms: 3,
    bathrooms: 2.5,
    square_feet: 1800,
    property_type: 'single_family',
    asking_price: 850000,
    estimated_value: 1050000,
    status: 'active',
    images: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop&crop=center"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockCompVisionAnalyses = [
  {
    id: "demo-1",
    address: "2847 Oakmont Drive",
    city: "Atlanta",
    state: "GA",
    zip_code: "30309",
    estimated_value: 485000,
    confidence: 92,
    image_url: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&h=600&fit=crop&crop=center",
    admin_approved: true,
    created_at: "2024-01-15T10:30:00Z",
    features: [
      { name: "Hardwood Floors", confidence: 95 },
      { name: "Granite Countertops", confidence: 88 },
      { name: "Stainless Appliances", confidence: 92 },
      { name: "Crown Molding", confidence: 85 },
      { name: "Fireplace", confidence: 90 },
      { name: "Updated Kitchen", confidence: 87 },
      { name: "Master Suite", confidence: 94 },
      { name: "Finished Basement", confidence: 82 },
      { name: "Two-Car Garage", confidence: 96 },
      { name: "Fenced Backyard", confidence: 89 }
    ],
    flip_comps: {
      after_repair_value: 625000,
      price_per_sqft: 285,
      days_on_market: 18,
      sale_to_list_ratio: 0.97,
      renovation_grade: "Moderate",
      recent_sales: [],
      lot_size: 0.28,
      zoning_potential: "Single Family Residential",
      neighborhood_trends: "Stable with 8% annual appreciation",
      property_type_match: "Traditional Single Family"
    },
    rental_comps: {
      market_rent_estimate: 3200,
      rent_to_price_ratio: 0.0066,
      cap_rate: 6.2,
      vacancy_rate: 4.5,
      tenant_turnover: "Low - stable neighborhood",
      crime_rate: "Below Average",
      school_district_quality: "Excellent - Top 15%", 
      transit_employment_access: "Good - 25min to downtown",
      hoa_fees: 0,
      property_taxes: 4850
    },
    similar_properties: [
      {
        id: "comp-1",
        address: "2891 Piedmont Avenue",
        similarity: 94,
        price: 472000,
        image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=150&h=100&fit=crop&crop=center",
        property_type: "Single Family",
        sqft: 1680,
        bedrooms: 3,
        bathrooms: 2
      },
      {
        id: "comp-2", 
        address: "1543 Virginia Highland",
        similarity: 89,
        price: 510000,
        image: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=150&h=100&fit=crop&crop=center",
        property_type: "Single Family",
        sqft: 1820,
        bedrooms: 4,
        bathrooms: 2
      },
      {
        id: "comp-3",
        address: "3021 Peachtree Road",
        similarity: 87,
        price: 495000,
        image: "https://images.unsplash.com/photo-1600585152225-3579fe9d9ae9?w=150&h=100&fit=crop&crop=center", 
        property_type: "Single Family",
        sqft: 1750,
        bedrooms: 3,
        bathrooms: 3
      }
    ]
  },
  {
    id: "demo-2",
    address: "1247 Industrial Boulevard",
    city: "Phoenix",
    state: "AZ", 
    zip_code: "85014",
    estimated_value: 285000,
    confidence: 88,
    image_url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop&crop=center",
    admin_approved: true,
    created_at: "2024-01-12T14:20:00Z",
    features: [
      { name: "Tile Flooring", confidence: 93 },
      { name: "Desert Landscaping", confidence: 96 },
      { name: "Solar Panels", confidence: 91 },
      { name: "Pool", confidence: 89 },
      { name: "Covered Patio", confidence: 94 },
      { name: "Vaulted Ceilings", confidence: 86 },
      { name: "Split Floor Plan", confidence: 88 },
      { name: "Double Car Garage", confidence: 95 }
    ],
    flip_comps: {
      after_repair_value: 375000,
      price_per_sqft: 195,
      days_on_market: 12,
      sale_to_list_ratio: 0.98,
      renovation_grade: "Light",
      recent_sales: [],
      lot_size: 0.22,
      zoning_potential: "Single Family Residential",
      neighborhood_trends: "Growing rapidly, 12% annual appreciation", 
      property_type_match: "Southwest Ranch Style"
    },
    rental_comps: {
      market_rent_estimate: 2400,
      rent_to_price_ratio: 0.0084,
      cap_rate: 8.5,
      vacancy_rate: 3.2,
      tenant_turnover: "Moderate - seasonal variations",
      crime_rate: "Average",
      school_district_quality: "Good - Top 35%",
      transit_employment_access: "Fair - suburban area",
      hoa_fees: 125,
      property_taxes: 2850
    },
    similar_properties: [
      {
        id: "comp-4",
        address: "1356 Camelback Ridge",
        similarity: 91,
        price: 295000,
        image: "https://images.unsplash.com/photo-1598228723793-52759bba239c?w=150&h=100&fit=crop&crop=center",
        property_type: "Single Family",
        sqft: 1450,
        bedrooms: 3,
        bathrooms: 2
      },
      {
        id: "comp-5",
        address: "2187 Scottsdale Way", 
        similarity: 86,
        price: 278000,
        image: "/api/placeholder/150/100",
        property_type: "Single Family",
        sqft: 1380,
        bedrooms: 2,
        bathrooms: 2
      }
    ]
  },
  {
    id: "demo-3",
    address: "456 Elmwood Avenue",
    city: "Buffalo",
    state: "NY",
    zip_code: "14222",
    estimated_value: 145000,
    confidence: 85,
    image_url: "https://images.unsplash.com/photo-1605146769289-440113cc3d00?w=800&h=600&fit=crop&crop=center",
    admin_approved: true,
    created_at: "2024-01-10T09:15:00Z",
    features: [
      { name: "Original Hardwood", confidence: 78 },
      { name: "High Ceilings", confidence: 92 },
      { name: "Bay Windows", confidence: 89 },
      { name: "Brick Exterior", confidence: 95 },
      { name: "Front Porch", confidence: 91 },
      { name: "Vintage Details", confidence: 83 },
      { name: "Basement", confidence: 87 },
      { name: "Mature Trees", confidence: 94 }
    ],
    flip_comps: {
      after_repair_value: 225000,
      price_per_sqft: 125,
      days_on_market: 35,
      sale_to_list_ratio: 0.94,
      renovation_grade: "Heavy",
      recent_sales: [],
      lot_size: 0.18,
      zoning_potential: "Single Family Residential",
      neighborhood_trends: "Gentrifying area, 15% appreciation",
      property_type_match: "Historic Colonial"
    },
    rental_comps: {
      market_rent_estimate: 1350,
      rent_to_price_ratio: 0.0093,
      cap_rate: 9.2,
      vacancy_rate: 6.8,
      tenant_turnover: "High - transitional neighborhood",
      crime_rate: "Above Average",
      school_district_quality: "Fair - Improving",
      transit_employment_access: "Excellent - downtown location",
      hoa_fees: 0,
      property_taxes: 3200
    },
    similar_properties: [
      {
        id: "comp-6",
        address: "723 Richmond Avenue",
        similarity: 88,
        price: 138000,
        image: "/api/placeholder/150/100",
        property_type: "Single Family",
        sqft: 1650,
        bedrooms: 3,
        bathrooms: 1
      },
      {
        id: "comp-7",
        address: "892 Delaware Street",
        similarity: 82,
        price: 159000,
        image: "/api/placeholder/150/100",
        property_type: "Single Family", 
        sqft: 1580,
        bedrooms: 4,
        bathrooms: 2
      }
    ]
  },
  {
    id: "demo-4",
    address: "8934 Oceanview Terrace",
    city: "San Diego",
    state: "CA",
    zip_code: "92109",
    estimated_value: 875000,
    confidence: 96,
    image_url: "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800&h=600&fit=crop&crop=center",
    admin_approved: true,
    created_at: "2024-01-08T16:45:00Z",
    features: [
      { name: "Ocean Views", confidence: 98 },
      { name: "Modern Kitchen", confidence: 94 },
      { name: "Open Floor Plan", confidence: 91 },
      { name: "Luxury Finishes", confidence: 89 },
      { name: "Walk-in Closet", confidence: 93 },
      { name: "En-suite Bathroom", confidence: 95 },
      { name: "Balcony/Deck", confidence: 92 },
      { name: "In-unit Laundry", confidence: 88 },
      { name: "Assigned Parking", confidence: 90 },
      { name: "Resort Amenities", confidence: 87 }
    ],
    flip_comps: {
      after_repair_value: 950000,
      price_per_sqft: 685,
      days_on_market: 8,
      sale_to_list_ratio: 1.02,
      renovation_grade: "None - Move-in Ready",
      recent_sales: [],
      lot_size: null,
      zoning_potential: "Multi-Family Residential",
      neighborhood_trends: "Premium market, 6% annual appreciation",
      property_type_match: "Luxury Condominium"
    },
    rental_comps: {
      market_rent_estimate: 4200,
      rent_to_price_ratio: 0.0048,
      cap_rate: 4.8,
      vacancy_rate: 2.1,
      tenant_turnover: "Very Low - luxury market",
      crime_rate: "Very Low",
      school_district_quality: "Excellent - Top 10%",
      transit_employment_access: "Excellent - beach community",
      hoa_fees: 485,
      property_taxes: 8750
    },
    similar_properties: [
      {
        id: "comp-8",
        address: "8756 Pacific Beach Drive",
        similarity: 95,
        price: 890000,
        image: "/api/placeholder/150/100",
        property_type: "Condominium",
        sqft: 1280,
        bedrooms: 2,
        bathrooms: 2
      },
      {
        id: "comp-9",
        address: "9201 Mission Bay Boulevard",
        similarity: 91,
        price: 825000,
        image: "/api/placeholder/150/100",
        property_type: "Condominium",
        sqft: 1180,
        bedrooms: 2,
        bathrooms: 2
      }
    ]
  },
  {
    id: "demo-5",
    address: "3456 Music Row",
    city: "Nashville",
    state: "TN",
    zip_code: "37203",
    estimated_value: 695000,
    confidence: 89,
    image_url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop&crop=center",
    admin_approved: true,
    created_at: "2024-01-05T11:30:00Z",
    features: [
      { name: "Exposed Brick", confidence: 94 },
      { name: "Industrial Elements", confidence: 91 },
      { name: "Loft-style Design", confidence: 88 },
      { name: "High Ceilings", confidence: 95 },
      { name: "Modern Fixtures", confidence: 87 },
      { name: "Rooftop Access", confidence: 83 },
      { name: "Downtown Location", confidence: 97 },
      { name: "Historic Building", confidence: 85 }
    ],
    flip_comps: {
      after_repair_value: 795000,
      price_per_sqft: 425,
      days_on_market: 15,
      sale_to_list_ratio: 0.99,
      renovation_grade: "Light Cosmetic",
      recent_sales: [],
      lot_size: null,
      zoning_potential: "Mixed Use Commercial/Residential",
      neighborhood_trends: "Hot market, 18% annual appreciation",
      property_type_match: "Urban Loft Conversion"
    },
    rental_comps: {
      market_rent_estimate: 3800,
      rent_to_price_ratio: 0.0055,
      cap_rate: 5.2,
      vacancy_rate: 3.8,
      tenant_turnover: "Moderate - young professional area",
      crime_rate: "Low",
      school_district_quality: "Good - Urban district",
      transit_employment_access: "Excellent - downtown core",
      hoa_fees: 225,
      property_taxes: 4875
    },
    similar_properties: [
      {
        id: "comp-10",
        address: "3789 Broadway Lofts",
        similarity: 92,
        price: 715000,
        image: "/api/placeholder/150/100",
        property_type: "Loft",
        sqft: 1650,
        bedrooms: 2,
        bathrooms: 2
      },
      {
        id: "comp-11",
        address: "4201 Gulch Condos",
        similarity: 87,
        price: 675000,
        image: "/api/placeholder/150/100",
        property_type: "Condominium",
        sqft: 1580,
        bedrooms: 2,
        bathrooms: 2
      }
    ]
  }
];
